color0 #12131c
color1 #ffb4ab
color2 #75d1ff
color3 #8ecff2
color4 #bec2ff
color5 #75d1ff
color6 #8ecff2
color7 #e3e1ef
color8 #8f8fa6
color9 #ffb4ab
color10 #75d1ff
color11 #8ecff2
color12 #bec2ff
color13 #75d1ff
color14 #8ecff2
color15 #e3e1ef

cursor                #e3e1ef
cursor_text_color     #12131c
background            #12131c
foreground            #e3e1ef
selection_foreground  #c5c4dd
selection_background  #444559
active_border_color   #75d1ff
inactive_border_color #444559
url_color             #75d1ff
