color0 #14121c
color1 #ffb4ab
color2 #cabeff
color3 #97ccf8
color4 #8fcdff
color5 #cabeff
color6 #97ccf8
color7 #e6e0ef
color8 #938ea5
color9 #ffb4ab
color10 #cabeff
color11 #97ccf8
color12 #8fcdff
color13 #cabeff
color14 #97ccf8
color15 #e6e0ef

cursor                #e6e0ef
cursor_text_color     #14121c
background            #14121c
foreground            #e6e0ef
selection_foreground  #c9c3dc
selection_background  #484459
url_color             #8fcdff