color0 #191019
color1 #ffb4ab
color2 #edb4eb
color3 #bcc3ff
color4 #bcc3ff
color5 #edb4eb
color6 #bcc3ff
color7 #efdeea
color8 #a18a9d
color9 #ffb4ab
color10 #edb4eb
color11 #bcc3ff
color12 #bcc3ff
color13 #edb4eb
color14 #bcc3ff
color15 #efdeea

cursor                #efdeea
cursor_text_color     #191019
background            #191019
foreground            #efdeea
selection_foreground  #d8bfd4
selection_background  #534152
url_color             #bcc3ff